### ISSUE TITLE
Dependency `node-sass` is deprecated

### ISSUE THREAD

**Issue by farooqkz** [farooqkz/KaiUIv2#3]
According to https://www.npmjs.com/package/node-sass it will still receive maintenance updates. But in long term, we'll have to move to something else.

**Comment by Simon-Laux** [comment]
the new way to use sass is https://github.com/sass/dart-sass afaik.
```
npm install --save-dev sass
```

**Comment by farooqkz** [comment]
Can you send a PR? @Simon-Laux

**Comment by Simon-Laux** [comment]
`npm install --save-dev sass`?

At the moment I don't see where node-sass is called currently in this repo, so I can not really replace it's usage.

After looking inside of [chooj](https://github.com/farooqkz/chooj) source I conclude that you could just remove node-sass as it was never really used here. chooj imports the scss file and it's bundler (parcel) compiles it.

**Comment by farooqkz** [comment]
> `npm install --save-dev sass`?
> 
> At the moment I don't see where node-sass is called currently in this repo, so I can not really replace it's usage.
> 
> After looking inside of [chooj](https://github.com/farooqkz/chooj) source I conclude that you could just remove node-sass as it was never really used here. chooj imports the scss file and it's bundler (parcel) compiles it.

yeah you are right. there is no dependency now :)
